refactor: use new lnd pending payments library method
GaloyMoney/galoy pull request #1180
Opened 2022-03-11 17:16 UTC by vindard

## Description

This is to update our internal `pending payments` and other lightning methods to reflect the changes in `lightning` introduced/uncovered in https://github.com/alexbosworth/lightning/pull/63

2022-04-05 15:04 UTC, dolcalmi requested changes

2022-04-05 15:04 UTC, dolcalmi commented on package.json
> +    "lightning": "^5.8.3",
to avoid future conflicts with yarn.lock file please remove `yarn.lock` and re-create it again with `yarn install`

2022-04-06 14:17 UTC, bodymindarts submitted a review, later dismissed

2022-04-25 23:11 UTC, dolcalmi approved these changes

2022-04-26 14:58 UTC, merged