feat: add new transactionsByWalletIds query for accounts
GaloyMoney/galoy pull request #1325
Opened 2022-05-23 20:30 UTC by vindard

## Description

This PR adds a new query under `Accounts` to be able to pass a list of wallet ids owned by the account to retrieve paginated transactions for.

2022-05-23 22:02 UTC, dolcalmi requested changes
Looks good, just a couple of comments. Also an e2e test is required.

2022-05-24 21:01 UTC, vindard commented on src/domain/accounts/account-validator.ts
> +        JSON.stringify({ accountId: account.id, accountIdFromWallet: wallet.accountId }),
Good point! https://github.com/GaloyMoney/galoy/pull/1325/commits/70c2fdc3922cee74fb2c30fe0fa7b6ceaadbe8e8

2022-05-24 21:05 UTC, UncleSamtoshi commented
Looks good to me! Only thing that could be nice is some kind of default to gather all transactions for an account without having to explicitly pass in there wallet ids.

2022-05-24 21:06 UTC, UncleSamtoshi approved these changes

2022-05-24 22:12 UTC, vindard commented on src/app/accounts/get-transactions-for-account.ts
> +import { Wallets } from "@app"
Done: https://github.com/GaloyMoney/galoy/pull/1325/commits/6816f9934f874c15e5f05ceebbd86db5a48cff12

2022-05-24 22:40 UTC, vindard commented
> Looks good to me! Only thing that could be nice is some kind of default to gather all transactions for an account without having to explicitly pass in there wallet ids.

Added 😉 https://github.com/GaloyMoney/galoy/pull/1325/commits/670d08fad62e6b05b7b2c2222ec67e04c013d9cc

2022-05-24 22:47 UTC, dolcalmi approved these changes

2022-05-24 22:49 UTC, UncleSamtoshi approved these changes

2022-05-24 23:42 UTC, dolcalmi approved these changes

2022-05-25 12:26 UTC, merged