chore: make it possible to filter internal IP address
GaloyMoney/galoy pull request #2065
Opened 2022-12-21 11:24 UTC by nicolasburtey

2022-12-21 19:45 UTC, dolcalmi reviewed
looks good, just a question...dont we want to use something more generic? like https://stackoverflow.com/a/13969691 or use a library like `ipaddr.js` https://github.com/whitequark/ipaddr.js/blob/master/test/ipaddr.test.js#L150

2022-12-22 09:48 UTC, nicolasburtey commented
> looks good, just a question...dont we want to use something more generic? like https://stackoverflow.com/a/13969691 or use a library like `ipaddr.js` https://github.com/whitequark/ipaddr.js/blob/master/test/ipaddr.test.js#L150

yeah that would remove the additional configuration parameter I have added. that is a good point. I'll do that.

2022-12-22 11:03 UTC, nicolasburtey commented
ok I think that is better. @dolcalmi let me know

2022-12-22 15:27 UTC, dolcalmi requested changes
looks good, just a minor change

2022-12-22 15:27 UTC, dolcalmi commented on test/unit/services/ipfetcher/fetch-ip-info.spec.ts
> +describe("ipaddr.js", () => {
this needs to be moved to test domain folder and description should be isPrivateIp (we are testing domain function here)

2022-12-23 13:04 UTC, merged