feat: whatsapp as an alternative way of receiving code
GaloyMoney/galoy pull request #2066
Opened 2022-12-21 12:56 UTC by nicolasburtey

2022-12-21 19:38 UTC, dolcalmi requested changes

2022-12-21 19:42 UTC, bodymindarts commented on src/graphql/main/mutations.ts
> +  captchaRequestAuthViaWhatsappCode: CaptchaRequestAuthCodeViaWhatsappMutation,
I had the same thought but I think best practice is actually to segregate on the mutation level. Or @samerbuna ?

2022-12-21 20:13 UTC, samerbuna commented on src/graphql/main/mutations.ts
> +  captchaRequestAuthViaWhatsappCode: CaptchaRequestAuthCodeViaWhatsappMutation,
I think one mutation might be a better option here, easier for clients, and gives us the option to make one a fallback for the other (if we want to do that in the future).

2022-12-21 23:27 UTC, dolcalmi requested changes
looks good, just minor changes

2022-12-21 23:27 UTC, dolcalmi commented on src/graphql/root/mutation/user-request-auth-code.ts
> +    const { phone, channel: channelInput } = args.input
you are missing `if (channelInput instanceof Error) ...`

2022-12-21 23:27 UTC, dolcalmi commented on src/domain/phone-provider/index.ts
> +  whatsapp: "whatsapp",
not a blocker but in the other "enums" we use capitalized names (please check CarrierType)

2022-12-22 09:48 UTC, daviroo approved these changes

2022-12-22 09:56 UTC, merged