chore: remove language custom resolver
GaloyMoney/galoy pull request #2885
Opened 2023-07-11 11:16 UTC by nicolasburtey

2023-07-20 05:49 UTC, dolcalmi requested changes

2023-07-20 05:49 UTC, dolcalmi commented on src/graphql/types/object/user.ts
this object is used too in admin queries... did you test it in that cases? that is the reason to have a custom resolver

2023-07-20 12:19 UTC, nicolasburtey commented on src/graphql/types/object/user.ts
I did not test this. that make sense but that also seems kind of an hacky/hidden behavior. will think about it a bit more.

2023-08-29 06:38 UTC, dolcalmi approved these changes

2023-09-04 11:16 UTC, merged