chore: add revert tx debug script
GaloyMoney/galoy pull request #2893
Opened 2023-07-12 21:55 UTC by krtk6160

2023-07-14 02:54 UTC, vindard requested changes
Tested locally, looks good to me for removing intraledger transactions. I don't think we'd need the lnd-related methods since we're only doing ledger operations here.

Do we plan to use this script for any transaction types other than intraledger ones?

2023-07-14 02:54 UTC, vindard commented on src/debug/revert-tx.ts
> +
```suggestion
```

2023-07-14 02:54 UTC, vindard commented on src/debug/revert-tx.ts
> +    await Promise.all(lndsConnect.map((lndParams) => isUp(lndParams)))
```suggestion
```

2023-07-20 05:44 UTC, dolcalmi commented
ummm this script is too dangerous... we need to have a script for specific cases with logic that guarantees at least basic business rules like `src/debug/void-payment.ts`

2023-09-13 18:51 UTC, dolcalmi commented
we can reopen it if it is necessary

2023-09-13 18:51 UTC, closed without merging