fix: properly handle null walletIds
GaloyMoney/galoy pull request #2998
Opened 2023-08-02 19:23 UTC by UncleSamtoshi

2023-08-02 19:53 UTC, dolcalmi requested changes

2023-08-02 19:53 UTC, dolcalmi commented on src/graphql/types/object/business-account.ts
> +        if (walletIds === undefined || walletIds === null) {
is not better just use `!walletIds`?

2023-08-04 17:49 UTC, UncleSamtoshi commented on src/graphql/types/object/business-account.ts
> +        if (walletIds === undefined || walletIds === null) {
Works for me

2023-09-14 01:17 UTC, dolcalmi approved these changes

2023-09-14 01:17 UTC, merged