chore: add account UUID migration
GaloyMoney/galoy pull request #3021
Opened 2023-08-07 22:15 UTC by dolcalmi

2023-08-07 22:23 UTC, ntheile submitted a review, later dismissed

2023-08-07 22:36 UTC, ntheile submitted a review, later dismissed

2023-08-08 07:38 UTC, nicolasburtey commented on src/migrations/20230807205306-add-uuid-to-accounts.ts
> +          update: { $set: { uuid } },
we call it `id` for the Wallet. I think we should keep the same pattern here ( `_id` for internal mongo object and `id` for the external identifier)

2023-08-08 07:38 UTC, nicolasburtey requested changes
I think we should be consistent and use `id` not `uuid`

2023-08-08 15:02 UTC, nicolasburtey commented
I've look into all the reference of account.id currently per your input and indeed it seems a big effort, so never mind my comment for now

2023-08-09 21:56 UTC, UncleSamtoshi approved these changes

2023-08-09 22:17 UTC, merged