test: move ln-send limits tests to bats
GaloyMoney/galoy pull request #3094
Opened 2023-08-20 15:50 UTC by vindard

2023-08-24 13:55 UTC, bodymindarts submitted a review, later dismissed

2023-08-24 19:42 UTC, dolcalmi requested changes
@vindard would you mind to do a rebase? yesterday I updated some packages and maybe we will need to apply changes spy on these changes too

2023-08-25 17:56 UTC, dolcalmi approved these changes

2023-08-25 18:10 UTC, dolcalmi approved these changes

2023-08-25 18:54 UTC, merged