test(core): move ledger volume tests
GaloyMoney/galoy pull request #3846
Opened 2024-01-16 16:25 UTC by vindard

## Description

This is an in-place move of volume tests with some refactoring to unroll the tests and make them more readable, and a fix to include `LnFeeReimbursement' to the payments transaction group.

A future iteration would be to also abstract the decision to use `outgoing` vs `incoming` into specific volume functions, instead of it being arbitrarily decided in use-cases.

2024-01-17 23:05 UTC, dolcalmi requested changes

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (internalVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (internalVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (internalNonVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (externalVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (externalNonVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (externalVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (externalNonVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (internalVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
> +        if (internalNonVolumeAffectingTypes.length) {
same here

2024-01-17 23:05 UTC, dolcalmi commented on core/api/test/integration/services/ledger-facade.spec.ts
this file needs to be splitted

2024-01-18 03:07 UTC, vindard commented on core/api/test/integration/services/ledger-facade.spec.ts
> +          describe("affects volume", () => {
Yup this one was tricky. The goal with this particular `volume by tx type` describe block is to take each volume method and then run every transaction type against it to check whether it affects the volume type or not. Example for one volume type, `External payment (withdrawal) txns`, these are the assertions and how they are categorised:

![image](https://github.com/GaloyMoney/galoy/assets/17693119/3ba58778-097b-4543-91f3-b92db3f7a26c)

This categorization is accomplished by simply defining an array like:
```ts
const externalPaymentTxTypes = [
    "Payment",
    "OnchainPayment",
    "LnFeeReimbursement",
    "LnFailedPayment",
]
```

We have 25 transaction types that can potentially affect each volume, and they are generally sorted into 5 categories. Each of these categories has a slightly different `it` implementation to check volumes against:
1. externalOut
1. externalIn
1. internalOut
1. internalIn
1. noEffect

For these 25 transaction types, we'd need some way to decide whether we will assert that they affect the volume or not.

The methodology I've come up with so far is to:
- group the transaction types into the 5 categories above
- define 2 tests for each category: asset affects volume, or asset does not affect volume
- define an array of the specific transaction types we expect to affect a given volume
- have code to use this array to sort each transaction types into its appropriate category of the 5 categories and then also decide whether to assert if it affects or does not affect the volume

If we were to roll out all these combinations into a distinct test by hand this test suite would become a lot bigger and trickier to reason about. So far this is the best way I've found to condense all the permutations/combinations of tx types that we need to check against each volume, which requires using some if statements in some places to help categorise our assertions and specific implementations of the volume check based on the tx type.

I'm open to other ideas on how we can do this without using the if statements. I'm not sure the right answer is to define every test case individually by hand.

2024-01-18 04:17 UTC, vindard commented on core/api/test/integration/services/ledger-facade.spec.ts
> +          describe("affects volume", () => {
Looking at this again, I think we can actually remove this entire describe. It was brought in when the volume code was a lot messier and the code is at the point now where we can probably test the txVolumeSince function more directly like we've started doing in #

2024-01-18 18:36 UTC, vindard commented on core/api/test/integration/services/ledger-facade.spec.ts
> +          describe.skip("does not affect volume", () => {
Is removed in #3870

2024-01-18 19:22 UTC, merged

2024-01-18 20:15 UTC, vindard commented
> approved because comments will be resolved after tests deletion

Resolved in #3876

2024-01-18 20:15 UTC, vindard commented on core/api/test/integration/services/ledger-facade.spec.ts
> +          describe("affects volume", () => {
Removed in #3876