refactor(notifications): persist language in notifications
GaloyMoney/galoy pull request #3887
Opened 2024-01-22 14:09 UTC by bodymindarts

2024-01-22 23:51 UTC, dolcalmi requested changes

2024-01-22 23:51 UTC, dolcalmi commented on core/api/src/app/users/get-user-language.ts
> +export const getUserLanguage = async (
I think this is not a proper approach. Language is not only used in notifications and from the domain pov is part of the user not notifications.

if notification sub system needs the language we will need to pass it through notification request or persist it too when the user change the language

2024-01-23 05:32 UTC, dolcalmi requested changes

2024-01-23 05:32 UTC, dolcalmi commented on core/api/src/services/notifications/index.ts
> +      const settings = await getUserNotificationSettings(recipient.userId)
this does not make sense, why do we want to persist settings in an external system if we will request them to then send them again to another method of the external system?

2024-01-23 06:42 UTC, thevaibhav-dixit commented on core/notifications/src/user_notification_settings/entity.rs
> +    // pub fn remove_push_device_token()
redundant comment ?

2024-01-24 08:35 UTC, closed without merging