chore(dashboard): added sats/cents in transaction table.
GaloyMoney/galoy pull request #4209
Opened 2024-03-19 08:52 UTC by siddhart1o1

2024-03-19 14:44 UTC, nicolasburtey requested changes
- for bitcoin wallet, sats should not be approximates
- I don't think we want to reduce the density of the table by having a double line on the amount

2024-03-20 05:07 UTC, siddhart1o1 commented
> * for bitcoin wallet, sats should not be approximates
> * I don't think we want to reduce the density of the table by having a double line on the amount

Updated 
According to @pretyflaco's suggestion,
"""
Display Currency that the payment is made in could be "Payment Amount" 
Currency that the settlement is made in could be "Settlement Amount" 
"""

2024-04-02 13:51 UTC, nicolasburtey commented
> > * for bitcoin wallet, sats should not be approximates
> > * I don't think we want to reduce the density of the table by having a double line on the amount
> 
> Updated According to @pretyflaco's suggestion, """ Display Currency that the payment is made in could be "Payment Amount" Currency that the settlement is made in could be "Settlement Amount" """

I think we're introducing a new language here (`Payment amount` is not something we have in our stack as of now). not sure this is ideal but for now I think that's ok.

2024-04-02 13:51 UTC, nicolasburtey approved these changes

2024-04-02 15:00 UTC, merged