[WIP] Auto-set display currency for level 1 users based on phone number prefix
GaloyMoney/galoy pull request #4271
Opened 2024-04-07 20:01 UTC by Prakhar-Agarwal-byte

2024-04-09 19:16 UTC, dolcalmi requested changes

2024-04-09 19:16 UTC, dolcalmi commented on core/api/src/app/accounts/create-account.ts
> +  account.displayCurrency = currency as DisplayCurrency
we need to validate against our list of currencies (we dont support all the currencies)

2024-04-17 13:51 UTC, vindard commented
@Prakhar-Agarwal-byte thanks for the contribution! I just updated the branch to remove some merge conflicts. Will you be continuing with this PR? There's some feedback from @dolcalmi to address

2024-04-19 17:06 UTC, closed without merging

2024-04-19 17:06 UTC, vindard commented
Closing in favour of a different approach we took to tackle this in #4309 and https://github.com/GaloyMoney/price/pull/67