feat(core): set display currency from country on account create
GaloyMoney/galoy pull request #4309
Opened 2024-04-18 03:04 UTC by vindard

2024-04-18 13:27 UTC, vindard commented on core/api/src/app/prices/display-currency-from-country-code.ts
> +export const displayCurrencyFromCountryCode = async (
I implemented this at app layer, but is it something that could/should live in price service instead?

2024-04-18 20:22 UTC, dolcalmi requested changes

2024-04-19 13:39 UTC, vindard commented on core/api/src/app/prices/display-currency-from-country-code.ts
> +): Promise<DisplayCurrency | false | ApplicationError> => {
Refactored here https://github.com/GaloyMoney/galoy/pull/4309/commits/fccc7cf45bc8a4df664f38bd6ce81ecf49bfd8df

2024-04-19 13:39 UTC, vindard commented on core/api/src/app/accounts/create-account.ts
> +    const displayCurrency = await displayCurrencyFromCountryCode(countryCode)
Refactored here https://github.com/GaloyMoney/galoy/pull/4309/commits/fccc7cf45bc8a4df664f38bd6ce81ecf49bfd8df

2024-04-19 13:57 UTC, vindard commented on core/api/src/app/prices/display-currency-from-country-code.ts
> +export const displayCurrencyFromCountryCode = async (
Moved to domain https://github.com/GaloyMoney/galoy/pull/4309/commits/fccc7cf45bc8a4df664f38bd6ce81ecf49bfd8df

2024-04-19 17:07 UTC, merged