Add placeholder query to playground
GaloyMoney/galoy pull request #804
Opened 2021-12-13 06:08 UTC by moksha256

To address #757.

Tested locally and worked fine.

Placeholder query is currently `btcPriceList` since it doesn't require authentication. This query also uses a variable, which may be useful for people to see. But let me know if you would prefer a different query.

2021-12-13 11:13 UTC, nicolasburtey commented
tests are not passing @moksha256 . you'll need to run prettier. `yarn prettier-write` should do it.

2021-12-13 19:00 UTC, moksha256 commented
> `yarn prettier-write` should do it.

Thanks, all checks now passed.

2021-12-13 19:25 UTC, samerbuna commented
Let's put the query text in a variable using a template string (using backticks and dropping the `\n`).  Define it in `src/graphql/playground.ts` and import it in `graphql-server.ts`

2021-12-13 19:26 UTC, samerbuna requested changes
Let's put the query text in a variable using a template string (using backticks and dropping the `\n`).  Define it in `src/graphql/playground.ts` and import it in `graphql-server.ts`

2021-12-13 19:35 UTC, vindard submitted a review, later dismissed
Looks good. Only suggestion I'd add is to potentially also have a `name` property on the tab, maybe something like `btcPriceList Sample Query`. Not a blocker though.

2021-12-14 17:56 UTC, moksha256 commented
@samerbuna @vindard thanks for the feedback. I added a tab name and defined all 3 query-related strings in `src/graphql/playground.ts` since it seemed like they should be together.

2021-12-14 18:45 UTC, vindard reviewed
Oh that makes sense collecting all the values in one file. I'm suggesting an alternative layout here that we can optionally use as well.

2021-12-14 18:45 UTC, vindard commented on src/graphql/playground.ts
> +export { defaultQuery, defaultQueryName, defaultQueryVars }
```suggestion
export const BTC_PRICE_QUERY = `query btcPriceList($range: PriceGraphRange!) {
  btcPriceList(range: $range) {
      timestamp
      price {
      base
      offset
      currencyUnit
      formattedAmount
    }
  }
}`

export const playgroundTabs = {
  default: {
    query: BTC_PRICE_QUERY,
    name: "btcPriceList (Sample Query)",
    variables: JSON.stringify({ range: "ONE_DAY" }),
  },
}

```

2021-12-14 18:45 UTC, vindard commented on src/servers/graphql-server.ts
> +              variables: defaultQueryVars,
```suggestion
              ...playgroundTabs.default,
```

2021-12-14 18:45 UTC, vindard commented on src/servers/graphql-server.ts
> +import { defaultQuery, defaultQueryName, defaultQueryVars } from "../graphql/playground"
```suggestion
import { playgroundTabs } from "../graphql/playground"
```

2021-12-15 18:08 UTC, moksha256 commented
Not sure if anyone else has feedback for vindard's changes so I just committed them and tested...looks good from my end.

2021-12-16 11:38 UTC, vindard approved these changes

2021-12-16 12:38 UTC, nicolasburtey approved these changes

2021-12-16 12:39 UTC, merged

2021-12-16 12:51 UTC, vindard commented
> Let's put the query text in a variable using a template string (using backticks and dropping the `\n`).

@samerbuna how would you drop the `\n` from the query string here?