chore: improve experience for when lnd is slow to respond
GaloyMoney/galoy pull request #852
Opened 2021-12-24 12:38 UTC by nicolasburtey

2021-12-24 14:30 UTC, vindard approved these changes
Is there any place that we run `getBalance` from where it's ok to be slow?

I'm wondering if there's somewhere that we can still expose the errors if any happen.

2021-12-24 14:33 UTC, dolcalmi requested changes

2021-12-24 14:33 UTC, dolcalmi commented on src/app/wallets/get-balance-for-wallet.ts
> +  // const [, updatePaymentsResult] =
please remove

2021-12-24 14:33 UTC, dolcalmi commented on src/app/wallets/get-balance-for-wallet.ts
> +  // if (updatePaymentsResult instanceof Error) throw updatePaymentsResult
please remove

2021-12-26 09:47 UTC, nicolasburtey commented
maybe a lot of the slow issues was related to the payment issues related to route hint? we may want to wait and see whether lnd is still slow to respond

2021-12-27 10:23 UTC, nicolasburtey commented
will close this for now. we'll see if the fix we did last week + @vindard PR on payment cleanup will resolve this.

2021-12-27 10:23 UTC, closed without merging