fix: addEarn method return handling in new graphql endpoint
GaloyMoney/galoy pull request #879
Opened 2021-12-30 21:34 UTC by vindard

## Description

This PR adds types to the `addEarn` use-case method and refactors the return type from that method. It also refactors some of the error types and handling in the method.

2022-01-04 14:07 UTC, vindard commented
_Responding to @daviroo's question about why we got the internal `Cannot read properties of undefined (reading 'id')` error exposed_

### How our error-handling works
Our error translation works in 2 ways:
- old-api: we would throw `CustomApolloError` child errors directly from the internal codebase to try to mitigate this. This has been mostly removed now and replaced by our new approach.

- new-api: we would catch and **return** all errors as `DomainError` types which would then be filtered at the graphql resolver layer and mapped (`mapError`) to a `CustomApolloError` type to be returned from the resolver. This is currently a manual process where we must:
  1. do an `instanceof Error` check on things returned from the domain, and
  2. pass any domain errors through `mapError` before attaching it to the resolvers returned object

### How it failed here
In this particular case, the internal error got through because:
- the use-case return wasn't properly typed so we didn't catch the index attempt on an object
- we used a `try-catch` at the graphql resolver layer, which could potentially bypass our `DomainError` handling which happened in this case

Avoiding this sort of thing is currently a manual process at the graphql layer that we're mostly able to avoid, but there can be cases like here where things slip through manual reviews.

### Potential mitigation
I'm not sure if there's a way to guarantee this doesn't happen via our automated checks, maybe via:
- typing returns at graphql layer so that things like the `err<any>.message` statement wouldn't pass lints, or
- having some sort of a wrapper on all resolvers to catch/translate (no idea how this might work)

2022-01-05 16:12 UTC, vindard commented
## Next Steps

We decided that we probably don't want to bubble up all instances of the errors that come back from the nested section since those can be user errors and not system errors. Ideally we'd like a way to distinguish between the two (exception vs. non-exception).

The next steps on this line of work would be to not create an error span event for all errors, but to instead:
- find a way to differentiate user vs system errors
- create span error events only for system errors
- bubble up span events to be captured by the honeycomb board (this PR)
- think about whether the dynamic mutation/query names in the attribute make sense for consistent query-ability

2022-01-07 17:40 UTC, vindard commented
@daviroo confirmed that the issue that was obscuring this on mobile end has been fixed and tested now, so this is ok to merge

2022-01-07 17:45 UTC, daviroo commented
I tested this locally and confirmed that the broken mutation is now fixed.  It would be good to make the phone validation optional in dev environment as right now this endpoint won't work in local dev unless you comment the phone validation out. I think that can be done in a separate change though as this fixes something which is currently broken.

2022-01-10 17:27 UTC, nicolasburtey commented on src/graphql/root/mutation/user-quiz-question-update-completed.ts
> +      accountId: uid,
`domainAccount.id` would be better type wise

2022-01-10 17:28 UTC, nicolasburtey reviewed
just one comment but looks good over otherwise

2022-01-10 17:28 UTC, nicolasburtey approved these changes

2022-01-10 17:33 UTC, dolcalmi requested changes
looks good, just minor comment/suggestions

2022-01-10 17:33 UTC, dolcalmi commented on src/graphql/root/mutation/user-quiz-question-update-completed.ts
> +      return { errors: [{ message: appErr.message || appErr.name }] }
map already assign appErr.name so you can remove `|| appErr.name`

2022-01-10 17:33 UTC, dolcalmi commented on src/app/accounts/add-earn.ts
> +  if (amount === undefined) return new InvalidQuizQuestionIdError()
```suggestion
  if (!amount) return new InvalidQuizQuestionIdError()
```

2022-01-10 17:56 UTC, dolcalmi approved these changes

2022-01-10 17:56 UTC, merged