Removing more core
GaloyMoney/galoy pull request #881
Opened 2022-01-02 13:44 UTC by nicolasburtey

2022-01-06 23:14 UTC, dolcalmi requested changes
looks good, just a couple of comments. @vindard please check before merge (although most of the changes are in the tests we need to be careful, specially with the projections)

2022-01-06 23:14 UTC, dolcalmi commented on test/integration/services/ledger/transaction.spec.ts
> +      sats: 1000 as Satoshis,
please use toSats (applies to other changes in this file)

2022-01-07 09:23 UTC, nicolasburtey commented on src/graphql/admin/root/query/transaction-by-id.ts
> -    if (ledgerTx instanceof CouldNotFindTransactionError) return null
good catch. I didn't meant to include it, but was pulled over from a rebase. removed.

2022-01-07 12:11 UTC, vindard reviewed
Left some comments about variable naming in the tests to be more specific. I'm ok to approve otherwise once [this change](https://github.com/GaloyMoney/galoy/pull/881/files#r780127012) is made

2022-01-07 12:36 UTC, nicolasburtey commented on test/integration/02-user-wallet/02-is-user-active.spec.ts
> +    const user0 = await getUserIdByTestUserIndex(0)
done

2022-01-07 12:36 UTC, nicolasburtey commented on test/integration/02-user-wallet/02-receive-lightning.spec.ts
> +let wallet1: WalletId
done

2022-01-07 12:36 UTC, nicolasburtey commented on test/integration/02-user-wallet/02-index.spec.ts
> +    account0 = await getAccountIdByTestUserIndex(0)
I suggest to do that in another PR

2022-01-07 12:36 UTC, nicolasburtey commented on test/integration/02-user-wallet/02-index.spec.ts
> +        ValidationError,
I suggest to do that in another PR

2022-01-07 12:36 UTC, nicolasburtey commented on test/integration/02-user-wallet/02-index.spec.ts
> +    account0 = await getAccountIdByTestUserIndex(0)
done

2022-01-07 12:37 UTC, nicolasburtey commented
> Left some comments about variable naming in the tests to be more specific. I'm ok to approve otherwise once [this change](https://github.com/GaloyMoney/galoy/pull/881/files#r780127012) is made

the link for this change doesn't work

2022-01-07 12:43 UTC, vindard approved these changes

2022-01-07 12:46 UTC, merged

2022-01-07 12:46 UTC, vindard commented
> @vindard please check before merge (although most of the changes are in the tests we need to be careful, specially with the projections)

@dolcalmi yup checked the projection against the translate function, and anything else in non-test code. Looked ok so far.